name: nntmux-ci

services:
  laravel.test:
    build:
      context: ..
      dockerfile: docker/8.5/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: nntmux-ci/php85
    environment:
      APP_ENV: testing
      COMPOSER_AUTH: '${COMPOSER_AUTH:-}'
      WWWUSER: '${WWWUSER}'
    volumes:
      - '..:/var/www/html'
