name: nntmux-ci

services:
  laravel.test:
    build:
      context: ../docker/8.5
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: nntmux-ci/php85
    environment:
      APP_ENV: testing
      COMPOSER_AUTH: '${COMPOSER_AUTH:-}'
      WWWUSER: '${WWWUSER}'
    volumes:
      - '..:/var/www/html'
