preset: laravel

risky: false

disabled:
    - no_tab_indentation

finder:
    exclude:
      - "tests"
      - "storage"
      - "vendor"
      - "docs"
      - "public/themes"
      - "libs"
      - "resources"
      - "database/migrations"
      - "database/seeds"