DROP TABLE IF EXISTS firewall;
CREATE TABLE firewall (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ip_address VARCHAR(39) NOT NULL,
  whitelisted TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY firewall_ip_address_unique (ip_address)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_unicode_ci
ROW_FORMAT=DYNAMIC;

