# Add foreign keys to user related tables. This patch might take some time

ALTER TABLE dnzb_failures ADD CONSTRAINT FK_users_df FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE forumpost ADD CONSTRAINT FK_users_fp FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE invitations ADD CONSTRAINT FK_users_inv FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE release_comments CHANGE users_id users_id INT(16) UNSIGNED NOT NULL;
ALTER TABLE users_releases ADD CONSTRAINT FK_users_ur FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_downloads ADD CONSTRAINT FK_users_ud FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_excluded_categories ADD CONSTRAINT FK_users_uec FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_movies ADD CONSTRAINT FK_users_um FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_requests ADD CONSTRAINT FK_users_urq FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_series ADD CONSTRAINT FK_users_us FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
