<?php

return [
    'db_name' => env('DB_DATABASE', 'nntmux'),
    'items_per_page' => env('ITEMS_PER_PAGE', 50),
    'items_per_cover_page' => env('ITEMS_PER_COVER_PAGE', 20),
    'max_pager_results' => env('MAX_PAGER_RESULTS', 125000),
    'flood_check' => env('FLOOD_CHECK', false),
    'flood_wait_time' => env('FLOOD_WAIT_TIME', 5),
    'flood_max_requests_per_second' => env('FLOOD_MAX_REQUESTS_PER_SECOND', 5),
    'echocli' => env('ECHOCLI', true),
    'rename_par2' => env('RENAME_PAR2', true),
    'rename_music_mediainfo' => env('RENAME_MUSIC_MEDIAINFO', true),
    'cache_expiry_short' => env('CACHE_EXPIRY_SHORT', 5),
    'cache_expiry_medium' => env('CACHE_EXPIRY_MEDIUM', 10),
    'cache_expiry_long' => env('CACHE_EXPIRY_LONG', 15),
    'admin_username' => env('ADMIN_USER', 'admin'),
    'admin_password' => env('ADMIN_PASS', 'admin'),
    'admin_email' => env('ADMIN_EMAIL', 'admin@example.com'),
    'multiprocessing_max_child_time' => env('NN_MULTIPROCESSING_MAX_CHILD_TIME', 1800),
    'multiprocessing_max_child_work' => env('NN_MULTIPROCESSING_MAX_CHILD_WORK', 1),
    'multiprocessing_max_children_override' => env('NN_MULTIPROCESSING_MAX_CHILDREN_OVERRIDE', 0),
    'multiprocessing_log_type' => env('NN_MULTIPROCESSING_LOG_TYPE', 6),
    'multiprocessing_child_output_type' => env('NN_MULTIPROCESSING_CHILD_OUTPUT_TYPE', 1),
    'purge_inactive_users' => env('PURGE_INACTIVE_USERS', false),
    'elasticsearch_enabled' => env('ELASTICSEARCH_ENABLED', false),
];
