INSERT INTO site (setting, value) VALUES
('sqlpatch',	'0'),
('categorizeforeign',	'1'),
('catwebdl',	'0'),
('giantbombkey', ''),
('lookupxxx', 1),
('maxxxxprocessed', 100),
('anidbkey', ''),
('alternate_nntp', '0'),
('amazonsleep', '1000'),
('maxaddprocessed', '25'),
('maxnfoprocessed', '100'),
('maxrageprocessed', '75'),
('maximdbprocessed', '100'),
('maxanidbprocessed', '100'),
('maxmusicprocessed', '150'),
('maxgamesprocessed', '150'),
('maxbooksprocessed', '300'),
('maxnzbsprocessed', '1000'),
('maxpartrepair', '15000'),
('partrepair', '1'),
('binarythreads', '1'),
('backfillthreads', '1'),
('safebackfilldate', '2012-06-24'),
('postthreads', '1'),
('releasethreads', '1'),
('nzbthreads', '1'),
('maxsizetopostprocess', '100'),
('minsizetopostprocess', '1'),
('postthreadsamazon', '1'),
('postthreadsnon', '1'),
('segmentstodownload', '2'),
('passchkattempts', '1'),
('maxpartsprocessed', '3'),
('trakttvkey', ''),
('fanarttvkey', ''),
('lookuppar2', '1'),
('addpar2', '1'),
('fixnamethreads', '1'),
('fixnamesperrun', '1'),
('zippath', ''),
('processjpg', '1'),
('scrape', '1'),
('nntpretries', '10'),
('imdburl', '0'),
('yydecoderpath', ''),
('ffmpeg_duration', '5'),
('ffmpeg_image_time', '5'),
('processvideos', '0'),
('maxsizetoprocessnfo', '100'),
('minsizetoprocessnfo', '1'),
('nfothreads', '1'),
('extractusingrarinfo', '0'),
('maxnestedlevels', '3'),
('innerfileblacklist', ''),
('miscotherretentionhours',	'0'),
('mischashedretentionhours',	'0'),
('maxnforetries', '5'),
('timeoutpath', ''),
('timeoutseconds', '0'),
('safepartrepair','0'),
('partrepairmaxtries', '3'),
('tablepergroup', '0'),
('nntpproxy','0'),
('book_reqids','7010'),
('intanidbupdate','7'),
('lastanidbupdate','0'),
('banned','0'),
('grabstatus', 1),
('crossposttime',	2),
('deletepossiblerelease', 0),
('nzbsplitlevel', 1),
('maxsizetoformrelease', 0),
('magic_file_path', ''),
('request_url', 'http://reqid.newznab-tmux.pw/'),
('userselstyle', '0');

ALTER TABLE  site
ADD  section VARCHAR(25)  NOT NULL DEFAULT '',
ADD  subsection VARCHAR(25)  NOT NULL DEFAULT '',
ADD  name    VARCHAR(25)  NOT NULL DEFAULT '',
ADD  hint   TEXT NOT NULL;
ALTER TABLE site DROP COLUMN id;
ALTER TABLE site DROP INDEX setting;
UPDATE site SET name = setting;
ALTER TABLE site
ADD PRIMARY KEY (section, subsection, name),
ADD UNIQUE INDEX ui_settings_setting (setting);
RENAME TABLE site TO settings;

DROP TABLE IF EXISTS tmux;
CREATE TABLE tmux
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    setting VARCHAR(64) NOT NULL,
    value VARCHAR(19000),
    updateddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX setting ON tmux (setting);

INSERT INTO tmux (setting, value) VALUES
('defrag_cache', '900'),
('monitor_delay', '30'),
('tmux_session', 'newznab'),
('niceness', '19'),
('binaries', '0'),
('maxbinaries', '10000'),
('backfill', '0'),
('import', '0'),
('nzbs', '/path/to/nzbs'),
('running', '0'),
('sequential', '0'),
('nfos', '0'),
('post', '0'),
('releases', '0'),
('fix_names', '0'),
('seq_timer', '30'),
('bins_timer', '30'),
('bins_kill_timer', '0'),
('back_timer', '30'),
('import_timer', '30'),
('rel_timer', '30'),
('fix_timer', '30'),
('post_timer', '30'),
('import_bulk', '0'),
('backfill_qty', '100000'),
('postprocess_kill', '0'),
('crap_timer', '30'),
('fix_crap', '0'),
('tv_timer', '43200'),
('update_tv', '0'),
('htop', '0'),
('nmon', '0'),
('bwmng', '0'),
('mytop', '0'),
('console', '0'),
('vnstat', '0'),
('vnstat_args', ''),
('tcptrack', '0'),
('tcptrack_args', '-i eth0 port 443'),
('backfill_groups', '4'),
('post_kill_timer', '300'),
('monitor_path', ''),
('write_logs', '0'),
('powerline', '0'),
('patchdb', '0'),
('patchdb_timer', '21600'),
('progressive', '0'),
('backfill_order', '2'),
('backfill_days', '1'),
('post_amazon', '0'),
('post_non', '0'),
('post_timer_amazon', '30'),
('post_timer_non', '30'),
('monitor_path_a', ''),
('monitor_path_b', ''),
('showquery', '0'),
('fix_crap_opt', 'Disabled'),
('showprocesslist', '0'),
('processupdate', '2'),
('maxmssgs', '20000'),
('currentppticket', '0'),
('nextppticket', '0'),
('debuginfo', '0'),
('sphinx', '0'),
('sphinx_timer', '600'),
('movie_timer', '43200'),
('fetch_movie', '0'),
('unwanted', '0'),
('others', '0'),
('spotnab', '0'),
('spotnab_timer', '600'),
('predb', '0'),
('predb_timer', '600'),
('request_hours', '1'),
('lastpretime', '0'),
('run_sharing', '0'),
('sharing_timer', '60'),
('optimize', '0'),
('optimize_timer', '86400'),
('import_count', '50000'),

DROP TABLE IF EXISTS prehash;
CREATE TABLE prehash (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    filename VARCHAR(255) DEFAULT '' NOT NULL,
    title VARCHAR(255) DEFAULT '' NOT NULL,
    nfo VARCHAR(255),
    size VARCHAR(50),
    category VARCHAR(255),
    predate DATETIME,
    source VARCHAR(50) DEFAULT '' NOT NULL,
    requestid INT UNSIGNED DEFAULT 0 NOT NULL,
    groupid INT UNSIGNED DEFAULT 0 NOT NULL,
    nuked TINYINT DEFAULT 0 NOT NULL,
    nukereason VARCHAR(255),
    files VARCHAR(50),
    searched TINYINT DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX ix_prehash_title ON prehash (title);
CREATE INDEX ix_prehash_category ON prehash (category);
CREATE INDEX ix_prehash_filename ON prehash (filename);
CREATE INDEX ix_prehash_nfo ON prehash (nfo);
CREATE INDEX ix_prehash_predate ON prehash (predate);
CREATE INDEX ix_prehash_requestid ON prehash (requestid, groupid);
CREATE INDEX ix_prehash_searched ON prehash (searched);
CREATE INDEX ix_prehash_size ON prehash (size);
CREATE INDEX ix_prehash_source ON prehash (source);

DROP TABLE IF EXISTS shortgroups;
CREATE TABLE shortgroups (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT '' NOT NULL,
    first_record BIGINT UNSIGNED DEFAULT 0 NOT NULL,
    last_record BIGINT UNSIGNED DEFAULT 0 NOT NULL,
    updated DATETIME
);
CREATE INDEX ix_shortgroups_id ON shortgroups (id);
CREATE INDEX ix_shortgroups_name ON shortgroups (name);

DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS countries;

CREATE TABLE countries (
  code CHAR(2) NOT NULL DEFAULT "",
  name VARCHAR(255) NOT NULL DEFAULT "",
  PRIMARY KEY (name)
) ENGINE=MYISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=1;

CREATE INDEX ix_countries_name ON countries (name);

INSERT INTO countries (code, name) VALUES
('AF', 'Afghanistan'),
('AX', 'Aland Islands'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AQ', 'Antarctica'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BV', 'Bouvetoya'),
('BR', 'Brazil'),
('VG', 'British Virgin Islands'),
('BN', 'Brunei Darussalam'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('CV', 'Cape Verde'),
('KY', 'Cayman Islands'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands'),
('CO', 'Colombia'),
('KM', 'Comoros the'),
('CD', 'Congo'),
('CG', 'Congo the'),
('CK', 'Cook Islands'),
('CR', 'Costa Rica'),
('CI', 'Cote d\'Ivoire'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Ethiopia'),
('FO', 'Faroe Islands'),
('FK', 'Falkland Islands'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GF', 'French Guiana'),
('PF', 'French Polynesia'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GD', 'Grenada'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IM', 'Isle of Man'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JE', 'Jersey'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', 'Korea, North'),
('KR', 'Korea, South'),
('KW', 'Kuwait'),
('KG', 'Kyrgyz Republic'),
('LA', 'Lao'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libyan Arab Jamahiriya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MK', 'Macedonia'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MX', 'Mexico'),
('FM', 'Micronesia'),
('MD', 'Moldova'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('AN', 'Netherlands Antilles'),
('NL', 'Netherlands'),
('NC', 'New Caledonia'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Norfolk Island'),
('MP', 'Northern Mariana Islands'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PS', 'Palestinian Territory'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PN', 'Pitcairn Islands'),
('PL', 'Poland'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('RE', 'Reunion'),
('RO', 'Romania'),
('RU', 'Russian Federation'),
('RW', 'Rwanda'),
('BL', 'Saint Barthelemy'),
('SH', 'Saint Helena'),
('KN', 'Saint Kitts'),
('LC', 'Saint Lucia'),
('MF', 'Saint Martin'),
('PM', 'Saint Pierre'),
('VC', 'Saint Vincent'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SZ', 'Swaziland'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syrian Arab Republic'),
('TW', 'Taiwan'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('VI', 'United States Virgin Islands'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Vietnam'),
('WF', 'Wallis and Futuna'),
('EH', 'Western Sahara'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');
