
ALTER TABLE users ADD COLUMN cp_api  VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN cp_url  VARCHAR(255) NULL DEFAULT NULL;
UPDATE `tmux` SET `value` = '65' WHERE `setting` = 'sqlpatch';
